name: run test and linter
on: push
jobs:
  linter_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.3]
    steps:
    - uses: actions/checkout@v3
    - name: install poetry
      run: pip install poetry
    - name: install dependencies
      run: poetry install
    - name: run pytest
      run: poetry run pytest
    - name: run lint
      run: poetry run ruff check gendiff
  coverage:
      needs: linter_and_test
      name: coverage
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry install
      - name: create reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: test
        run: poetry run pytest --cov --cov-report xml
      - name: sending reporter
        env:
          GITHUB_TOKEN: 4b9e40fd4e59d501521eca7e1f4d7dc1610d47bd4fdcca395398ca0e28f68b86
        run: ./cc-test-reporter after-build -r "$GITHUB_TOKEN"
